# Generated by Django 5.1.3 on 2024-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('employee_position', models.CharField(max_length=255)),
            ],
        ),
    ]
