# Generated by Django 5.1.3 on 2024-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_image_table_alter_videoreview_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
