# Generated by Django 5.1.3 on 2024-11-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_videoreview_published_at_videoreview_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoreview',
            name='project',
        ),
    ]
